import static org.junit.Assert.*;
import org.junit.Test;

public class NewEmptyJUnitTest {

    /**
     *
     */
    @Test
    public void NewEmptyJUnitTest() {
        assertEquals("error in add()", 3, calculator1.add(1, 2));
        assertEquals("error in add()", -3, calculator1.add(-1, -2));
        assertEquals("error in add()", 9, calculator1.add(9, 0));
    }

    public void NewEmptyJUnitTestaddFail() {
        assertEquals("error in add()", 0, calculator1.add(1, 2));
    }

    public void NewEmptyJUnitTestsubpass() {
        assertEquals("error in sub()", 1, calculator1.add(1, 2));
        assertEquals("error in sub()", -1, calculator1.add(-1, -2));
        assertEquals("error in sub()", 0, calculator1.add(2, 1));
    }

    public void NewEmptyJUnitsubFail() {

        assertEquals("error in add()", 0, calculator1.add(2, 1));

    }

}
